### ISSUE TITLE
What about a drive image as the OS is not archived

### ISSUE THREAD

**Issue by BlizzardfurMeow** [misterblack1/plexus-p20#4]
it would be good if it was archived here

**Comment by artgreen** [comment]
I was watching the show and I came here to look for the disk image too.  I'd love to look back and see how things have changed, and not changed, for UNIX over the years.

**Comment by sebras** [comment]
@Blizzardfur-Maxxx @artgreen did you guys look at the first entry here? https://archive.org/details/@misteradrianblack

**Comment by ewenmcneill** [comment]
FYI, a sanitised version of the drive image was added to this git repo a few days ago:

https://github.com/misterblack1/plexus-p20/tree/main/disk

(The "hidden partition" and "user partition" had quite a bit removed -- all of the "hidden partition" which was the old user partition from its earlier life I believe., because there was lots of private information on them.   But some of the relevant files extract from that partition have also been added separately.)

So possibly this issue can be closed now?

Ewen

PS: As sebras noted, it looks like the sanitised hard drive image also got uploaded to the Internet Archive -- https://archive.org/details/plexus-sanitized.emu
